version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && npm start'
    image: none
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"  # Needed for the ACME HTTP-01 challenge.
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./services/caddy/caddy-config:/config
      - ./services/caddy/caddy-data:/data
      - ./services/caddy/test_code:/wdata
    depends_on:
      - app